import { describe, it, expect } from "vitest";
import { getLevelInfo, getPointsToNextLevel, getPointsIntoLevel } from "./gamification";

describe("getPointsIntoLevel", () => {
  it("is 0 at the exact start of a level band", () => {
    // Level 5 "Momentum" starts at 850
    expect(getPointsIntoLevel(850)).toBe(0);
  });

  it("counts points earned since entering the current band", () => {
    // 1000 is 150 into the 850–1299 band (the case where the old
    // `totalPoints % 1000` formula wrongly rendered the bar at 0%)
    expect(getPointsIntoLevel(1000)).toBe(150);
    expect(getPointsIntoLevel(900)).toBe(50);
  });

  it("never goes negative and stays inside the band width", () => {
    for (let p = 0; p <= 5000; p += 37) {
      const into = getPointsIntoLevel(p);
      expect(into).toBeGreaterThanOrEqual(0);
    }
  });
});

describe("level progress invariant", () => {
  // The dashboard renders pointsIntoLevel / (pointsIntoLevel + pointsToNextLevel).
  // For every non-max level, that sum must equal the band's full width, so the
  // fraction is a true 0..<100% position within the level.
  it("pointsIntoLevel + pointsToNextLevel equals the band span below max level", () => {
    for (const totalPoints of [0, 50, 99, 100, 250, 500, 849, 850, 1000, 1299, 1300, 4099]) {
      const info = getLevelInfo(totalPoints);
      const span = info.maxPoints + 1 - info.minPoints;
      expect(getPointsIntoLevel(totalPoints) + getPointsToNextLevel(totalPoints)).toBe(span);
    }
  });

  it("computed percentage matches the true position within the band", () => {
    const pct = (p: number) => {
      const span = getPointsIntoLevel(p) + getPointsToNextLevel(p);
      return span > 0 ? (getPointsIntoLevel(p) / span) * 100 : 100;
    };
    expect(pct(1000)).toBeCloseTo((150 / 450) * 100, 5); // ~33.3%, NOT 0%
    expect(pct(900)).toBeCloseTo((50 / 450) * 100, 5);   // ~11.1%, NOT 90%
    expect(pct(850)).toBe(0);
  });

  it("always has a next level to climb (no ceiling)", () => {
    // Apex (level 10) is no longer the top — the ladder is endless, so there
    // is always positive progress remaining toward the next level.
    expect(getPointsToNextLevel(4100)).toBe(950); // 5050 (L11 start) − 4100
    expect(getPointsToNextLevel(31300)).toBeGreaterThan(0); // even at L26
    expect(getPointsToNextLevel(1_000_000)).toBeGreaterThan(0); // and far beyond
  });
});

describe("endless leveling past Apex", () => {
  // Levels are generated by minPoints(n) = 50·((n−1)² + 1) for n ≥ 2 (0 at L1),
  // which reproduces the original 1–10 table exactly and continues forever.

  it("keeps levels 1–10 identical to the original table", () => {
    const original: Array<[number, number, string]> = [
      [0, 1, "Spark"], [100, 2, "Ignite"], [250, 3, "Focus"], [500, 4, "Flow"],
      [850, 5, "Momentum"], [1300, 6, "Drive"], [1850, 7, "Surge"],
      [2500, 8, "Blaze"], [3250, 9, "Vortex"], [4100, 10, "Apex"],
    ];
    for (const [points, level, name] of original) {
      const info = getLevelInfo(points);
      expect(info.level).toBe(level);
      expect(info.name).toBe(name);
      expect(info.minPoints).toBe(points);
    }
  });

  it("names the new tiers 11–26 and unlocks the gated catalog levels", () => {
    expect(getLevelInfo(5050).level).toBe(11);
    expect(getLevelInfo(5050).name).toBe("Nova");
    expect(getLevelInfo(9850).level).toBe(15);   // Stormpike Glaive (levelRequired 15)
    expect(getLevelInfo(28850).level).toBe(25);  // Excalibur / Staff of the Archmage
    expect(getLevelInfo(31300).level).toBe(26);
    expect(getLevelInfo(31300).name).toBe("Eternal"); // Dragonscale Plate (levelRequired 26)
  });

  it("labels endless levels past 26 as Paragon tiers", () => {
    // minPoints(30) = 50·(29² + 1) = 42100
    expect(getLevelInfo(42100).level).toBe(30);
    expect(getLevelInfo(42100).name).toBe("Paragon 4"); // 30 − 26
  });

  it("crosses the 26→27 boundary cleanly", () => {
    // minPoints(27) = 50·(26² + 1) = 33850
    expect(getLevelInfo(33849).level).toBe(26);
    expect(getLevelInfo(33850).level).toBe(27);
    expect(getLevelInfo(33850).name).toBe("Paragon 1");
  });

  it("never lets level decrease as points increase (monotonic)", () => {
    let prev = 0;
    for (let p = 0; p <= 60000; p += 13) {
      const level = getLevelInfo(p).level;
      expect(level).toBeGreaterThanOrEqual(prev);
      prev = level;
    }
  });

  it("keeps the into+toNext = band span invariant at high levels", () => {
    for (const p of [5050, 9850, 22100, 31300, 33850, 42100]) {
      const info = getLevelInfo(p);
      const span = info.maxPoints + 1 - info.minPoints;
      expect(getPointsIntoLevel(p) + getPointsToNextLevel(p)).toBe(span);
    }
  });
});
