import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import tasksRouter from "./tasks";
import momentumRouter from "./momentum";
import badgesRouter from "./badges";
import accountabilityRouter from "./accountability";
import leaderboardRouter from "./leaderboard";
import notificationsRouter from "./notifications";
import recurringTasksRouter from "./recurring-tasks";
import avatarRouter from "./avatar";
import gearRouter from "./gear";
import battleRouter from "./battle";
import worldBossRouter from "./world-boss";
import dopamineRewardsRouter from "./dopamine-rewards";
import cronRouter from "./cron";
import calendarRouter from "./calendar";
import focusSessionsRouter from "./focus-sessions";
import questlinesRouter from "./questlines";
import brainRouter from "./brain";
import rescueRouter from "./rescue";
import coinsRouter from "./coins";
import rewardsStoreRouter from "./rewards-store";

const router: IRouter = Router();

router.use(healthRouter);
router.use(cronRouter);
router.use(authRouter);
router.use(usersRouter);
// /tasks/momentum must beat tasksRouter's /tasks/:id — order matters.
router.use(momentumRouter);
router.use(tasksRouter);
router.use(recurringTasksRouter);
router.use(badgesRouter);
router.use(accountabilityRouter);
router.use(leaderboardRouter);
router.use(notificationsRouter);
router.use(avatarRouter);
router.use(gearRouter);
router.use(battleRouter);
router.use(worldBossRouter);
router.use(dopamineRewardsRouter);
router.use(calendarRouter);
router.use(focusSessionsRouter);
router.use(questlinesRouter);
router.use(brainRouter);
router.use(rescueRouter);
router.use(coinsRouter);
router.use(rewardsStoreRouter);

export default router;
