import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import accountRouter from "./account";
import tasksRouter from "./tasks";
import momentumRouter from "./momentum";
import badgesRouter from "./badges";
import accountabilityRouter from "./accountability";
import bodyDoubleRouter from "./body-double";
import leaderboardRouter from "./leaderboard";
import notificationsRouter from "./notifications";
import devicesRouter from "./devices";
import recurringTasksRouter from "./recurring-tasks";
import avatarRouter from "./avatar";
import gearRouter from "./gear";
import battleRouter from "./battle";
import worldBossRouter from "./world-boss";
import encounterRouter from "./encounter";
import dopamineRewardsRouter from "./dopamine-rewards";
import cronRouter from "./cron";
import calendarRouter from "./calendar";
import focusSessionsRouter from "./focus-sessions";
import questlinesRouter from "./questlines";
import campaignsRouter from "./campaigns";
import brainRouter from "./brain";
import rescueRouter from "./rescue";
import coinsRouter from "./coins";
import rewardsStoreRouter from "./rewards-store";
import mysteryBoxRouter from "./mystery-box";
import statPerksRouter from "./stat-perks";
import patternsRouter from "./patterns";
import reflectionsRouter from "./reflections";
import recapsRouter from "./recaps";
import shortcutTokensRouter from "./shortcut-tokens";
import shortcutsRouter from "./shortcuts";

const router: IRouter = Router();

router.use(healthRouter);
router.use(cronRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(accountRouter);
router.use(shortcutTokensRouter);
// /tasks/momentum must beat tasksRouter's /tasks/:id — order matters.
router.use(momentumRouter);
router.use(tasksRouter);
router.use(shortcutsRouter);
router.use(recurringTasksRouter);
router.use(badgesRouter);
router.use(accountabilityRouter);
router.use(bodyDoubleRouter);
router.use(leaderboardRouter);
router.use(notificationsRouter);
router.use(devicesRouter);
router.use(avatarRouter);
router.use(gearRouter);
router.use(battleRouter);
router.use(worldBossRouter);
router.use(encounterRouter);
router.use(dopamineRewardsRouter);
router.use(calendarRouter);
router.use(focusSessionsRouter);
router.use(questlinesRouter);
router.use(campaignsRouter);
router.use(brainRouter);
router.use(rescueRouter);
router.use(coinsRouter);
router.use(rewardsStoreRouter);
router.use(mysteryBoxRouter);
router.use(statPerksRouter);
router.use(patternsRouter);
router.use(reflectionsRouter);
router.use(recapsRouter);

export default router;
