// AUTO-GENERATED by scripts/src/build-lpc-assets.ts — do not edit by hand.
// Regenerate with: pnpm --filter @workspace/scripts build-lpc
import type { CatalogEntry } from "./types";

export const CATALOG: CatalogEntry[] = [
  {
    "id": "body:male:light",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/male_light.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:male:tan",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/male_tan.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:male:brown",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/male_brown.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:male:dark",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/male_dark.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:male:green",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/male_green.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:male:blue",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/male_blue.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:female:light",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/female_light.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:female:tan",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/female_tan.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:female:brown",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/female_brown.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:female:dark",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/female_dark.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:female:green",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/female_green.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:female:blue",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/female_blue.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "hair:short:brown",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/short_brown.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:short:black",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/short_black.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:short:blonde",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/short_blonde.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:short:red",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/short_red.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:short:white",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/short_white.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:short:blue",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/short_blue.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:long:brown",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/long_brown.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:long:black",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/long_black.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:long:blonde",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/long_blonde.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:long:red",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/long_red.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:long:white",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/long_white.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:long:blue",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/long_blue.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:ponytail:brown",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/ponytail_brown.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:ponytail:black",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/ponytail_black.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:ponytail:blonde",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/ponytail_blonde.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:ponytail:red",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/ponytail_red.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:ponytail:white",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/ponytail_white.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:ponytail:blue",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/ponytail_blue.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:afro:brown",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/afro_brown.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:afro:black",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/afro_black.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:afro:blonde",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/afro_blonde.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:afro:red",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/afro_red.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:afro:white",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/afro_white.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:afro:blue",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/afro_blue.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  }
];

export const catalogById: Map<string, CatalogEntry> = new Map(
  CATALOG.map((e) => [e.id, e]),
);
