// AUTO-GENERATED by scripts/src/build-lpc-assets.ts — do not edit by hand.
// Regenerate with: pnpm --filter @workspace/scripts build-lpc
import type { CatalogEntry } from "./types";

export const CATALOG: CatalogEntry[] = [
  {
    "id": "body:male:light",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/male_light.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:male:tan",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/male_tan.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:male:brown",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/male_brown.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:male:dark",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/male_dark.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:male:green",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/male_green.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:male:blue",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/male_blue.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:male:olive",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/male_olive.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:male:bronze",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/male_bronze.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:male:almond",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/male_almond.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:female:light",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/female_light.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:female:tan",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/female_tan.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:female:brown",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/female_brown.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:female:dark",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/female_dark.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:female:green",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/female_green.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:female:blue",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/female_blue.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:female:olive",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/female_olive.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:female:bronze",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/female_bronze.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "body:female:almond",
    "category": "body",
    "zIndex": 10,
    "file": "/lpc/body/female_almond.png",
    "author": "bluecarrot16; JaidynReiman; Benjamin K. Smith (BenCreating); ElizaWy; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-character-bases"
  },
  {
    "id": "hair:short:brown",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/short_brown.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:short:black",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/short_black.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:short:blonde",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/short_blonde.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:short:red",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/short_red.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:short:white",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/short_white.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:short:blue",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/short_blue.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:short:gray",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/short_gray.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:short:auburn",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/short_auburn.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:short:green",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/short_green.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:short:purple",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/short_purple.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:short:pink",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/short_pink.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:short:orange",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/short_orange.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:long:brown",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/long_brown.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:long:black",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/long_black.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:long:blonde",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/long_blonde.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:long:red",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/long_red.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:long:white",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/long_white.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:long:blue",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/long_blue.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:long:gray",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/long_gray.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:long:auburn",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/long_auburn.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:long:green",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/long_green.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:long:purple",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/long_purple.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:long:pink",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/long_pink.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:long:orange",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/long_orange.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:ponytail:brown",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/ponytail_brown.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:ponytail:black",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/ponytail_black.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:ponytail:blonde",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/ponytail_blonde.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:ponytail:red",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/ponytail_red.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:ponytail:white",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/ponytail_white.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:ponytail:blue",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/ponytail_blue.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:ponytail:gray",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/ponytail_gray.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:ponytail:auburn",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/ponytail_auburn.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:ponytail:green",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/ponytail_green.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:ponytail:purple",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/ponytail_purple.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:ponytail:pink",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/ponytail_pink.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:ponytail:orange",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/ponytail_orange.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:afro:brown",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/afro_brown.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:afro:black",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/afro_black.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:afro:blonde",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/afro_blonde.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:afro:red",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/afro_red.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:afro:white",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/afro_white.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:afro:blue",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/afro_blue.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:afro:gray",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/afro_gray.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:afro:auburn",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/afro_auburn.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:afro:green",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/afro_green.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:afro:purple",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/afro_purple.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:afro:pink",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/afro_pink.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:afro:orange",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/afro_orange.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bob:brown",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bob_brown.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bob:black",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bob_black.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bob:blonde",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bob_blonde.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bob:red",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bob_red.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bob:white",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bob_white.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bob:blue",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bob_blue.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bob:gray",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bob_gray.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bob:auburn",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bob_auburn.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bob:green",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bob_green.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bob:purple",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bob_purple.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bob:pink",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bob_pink.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bob:orange",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bob_orange.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:curly:brown",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/curly_brown.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:curly:black",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/curly_black.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:curly:blonde",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/curly_blonde.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:curly:red",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/curly_red.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:curly:white",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/curly_white.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:curly:blue",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/curly_blue.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:curly:gray",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/curly_gray.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:curly:auburn",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/curly_auburn.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:curly:green",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/curly_green.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:curly:purple",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/curly_purple.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:curly:pink",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/curly_pink.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:curly:orange",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/curly_orange.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:spiked:brown",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/spiked_brown.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:spiked:black",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/spiked_black.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:spiked:blonde",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/spiked_blonde.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:spiked:red",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/spiked_red.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:spiked:white",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/spiked_white.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:spiked:blue",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/spiked_blue.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:spiked:gray",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/spiked_gray.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:spiked:auburn",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/spiked_auburn.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:spiked:green",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/spiked_green.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:spiked:purple",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/spiked_purple.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:spiked:pink",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/spiked_pink.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:spiked:orange",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/spiked_orange.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bangs:brown",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bangs_brown.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bangs:black",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bangs_black.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bangs:blonde",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bangs_blonde.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bangs:red",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bangs_red.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bangs:white",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bangs_white.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bangs:blue",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bangs_blue.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bangs:gray",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bangs_gray.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bangs:auburn",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bangs_auburn.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bangs:green",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bangs_green.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bangs:purple",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bangs_purple.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bangs:pink",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bangs_pink.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:bangs:orange",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/bangs_orange.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:pixie:brown",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/pixie_brown.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:pixie:black",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/pixie_black.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:pixie:blonde",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/pixie_blonde.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:pixie:red",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/pixie_red.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:pixie:white",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/pixie_white.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:pixie:blue",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/pixie_blue.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:pixie:gray",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/pixie_gray.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:pixie:auburn",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/pixie_auburn.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:pixie:green",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/pixie_green.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:pixie:purple",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/pixie_purple.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:pixie:pink",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/pixie_pink.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "hair:pixie:orange",
    "category": "hair",
    "zIndex": 30,
    "file": "/lpc/hair/pixie_orange.png",
    "author": "bluecarrot16; Manuel Riecke (MrBeast); JaidynReiman; ElizaWy",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-hair"
  },
  {
    "id": "beard:stubble:brown",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/stubble_brown.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:stubble:black",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/stubble_black.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:stubble:blonde",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/stubble_blonde.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:stubble:red",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/stubble_red.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:stubble:white",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/stubble_white.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:stubble:blue",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/stubble_blue.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:stubble:gray",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/stubble_gray.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:stubble:auburn",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/stubble_auburn.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:stubble:green",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/stubble_green.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:stubble:purple",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/stubble_purple.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:stubble:pink",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/stubble_pink.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:stubble:orange",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/stubble_orange.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:short:brown",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/short_brown.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:short:black",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/short_black.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:short:blonde",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/short_blonde.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:short:red",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/short_red.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:short:white",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/short_white.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:short:blue",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/short_blue.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:short:gray",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/short_gray.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:short:auburn",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/short_auburn.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:short:green",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/short_green.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:short:purple",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/short_purple.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:short:pink",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/short_pink.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:short:orange",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/short_orange.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:full:brown",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/full_brown.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:full:black",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/full_black.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:full:blonde",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/full_blonde.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:full:red",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/full_red.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:full:white",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/full_white.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:full:blue",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/full_blue.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:full:gray",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/full_gray.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:full:auburn",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/full_auburn.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:full:green",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/full_green.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:full:purple",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/full_purple.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:full:pink",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/full_pink.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:full:orange",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/full_orange.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:mustache:brown",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/mustache_brown.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:mustache:black",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/mustache_black.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:mustache:blonde",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/mustache_blonde.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:mustache:red",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/mustache_red.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:mustache:white",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/mustache_white.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:mustache:blue",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/mustache_blue.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:mustache:gray",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/mustache_gray.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:mustache:auburn",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/mustache_auburn.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:mustache:green",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/mustache_green.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:mustache:purple",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/mustache_purple.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:mustache:pink",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/mustache_pink.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "beard:mustache:orange",
    "category": "beard",
    "zIndex": 20,
    "file": "/lpc/beard/mustache_orange.png",
    "author": "JaidynReiman; Thane Brimhall (pennomi); laetissima; ElizaWy; bluecarrot16; Carlo Enrico Victoria (Nemisys)",
    "license": "CC-BY-SA 3.0, GPL 3.0, OGA-BY 3.0, CC0",
    "sourceUrl": "https://opengameart.org/content/lpc-base-character-expressions"
  },
  {
    "id": "outfit:fighter:t0:male",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/fighter_t0_male.png",
    "author": "JaidynReiman; bluecarrot16; Johannes Sjölund (wulax); Joe White; ElizaWy; Matthew Krohn (makrohn); Stephen Challener (Redshrike)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "outfit:fighter:t0:female",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/fighter_t0_female.png",
    "author": "JaidynReiman; bluecarrot16; Johannes Sjölund (wulax); Joe White; ElizaWy; Matthew Krohn (makrohn); Stephen Challener (Redshrike)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "outfit:fighter:t1:male",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/fighter_t1_male.png",
    "author": "Matthew Krohn (makrohn); Johannes Sjölund (wulax); bluecarrot16; JaidynReiman; Michael Whitlock (bigbeargames)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "outfit:fighter:t1:female",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/fighter_t1_female.png",
    "author": "Matthew Krohn (makrohn); Johannes Sjölund (wulax); bluecarrot16; JaidynReiman; Michael Whitlock (bigbeargames)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "outfit:fighter:t2:male",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/fighter_t2_male.png",
    "author": "Matthew Krohn (makrohn); Johannes Sjölund (wulax); bluecarrot16; JaidynReiman; Michael Whitlock (bigbeargames); Napsio (Vitruvian Studio)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "outfit:fighter:t2:female",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/fighter_t2_female.png",
    "author": "Matthew Krohn (makrohn); Johannes Sjölund (wulax); bluecarrot16; JaidynReiman; Michael Whitlock (bigbeargames); Napsio (Vitruvian Studio)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "outfit:fighter:t3:male",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/fighter_t3_male.png",
    "author": "Matthew Krohn (makrohn); Johannes Sjölund (wulax); bluecarrot16; JaidynReiman; Michael Whitlock (bigbeargames); Napsio (Vitruvian Studio)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "outfit:fighter:t3:female",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/fighter_t3_female.png",
    "author": "Matthew Krohn (makrohn); Johannes Sjölund (wulax); bluecarrot16; JaidynReiman; Michael Whitlock (bigbeargames); Napsio (Vitruvian Studio)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "outfit:ranger:t0:male",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/ranger_t0_male.png",
    "author": "JaidynReiman; bluecarrot16; Johannes Sjölund (wulax); Joe White; ElizaWy; Matthew Krohn (makrohn); Stephen Challener (Redshrike)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "outfit:ranger:t0:female",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/ranger_t0_female.png",
    "author": "JaidynReiman; bluecarrot16; Johannes Sjölund (wulax); Joe White; ElizaWy; Matthew Krohn (makrohn); Stephen Challener (Redshrike)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "outfit:ranger:t1:male",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/ranger_t1_male.png",
    "author": "JaidynReiman; bluecarrot16; Nila122; ElizaWy; Matthew Krohn (makrohn); Johannes Sjölund (wulax); Stephen Challener (Redshrike); Joe White; Michael Whitlock (bigbeargames)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 2.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-clothes-and-hair"
  },
  {
    "id": "outfit:ranger:t1:female",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/ranger_t1_female.png",
    "author": "JaidynReiman; bluecarrot16; Nila122; ElizaWy; Matthew Krohn (makrohn); Johannes Sjölund (wulax); Stephen Challener (Redshrike); Joe White; Michael Whitlock (bigbeargames)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 2.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-clothes-and-hair"
  },
  {
    "id": "outfit:ranger:t2:male",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/ranger_t2_male.png",
    "author": "JaidynReiman; bluecarrot16; Nila122; Michael Whitlock (bigbeargames); Matthew Krohn (makrohn); Johannes Sjölund (wulax)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 2.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-clothes-and-hair"
  },
  {
    "id": "outfit:ranger:t2:female",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/ranger_t2_female.png",
    "author": "JaidynReiman; bluecarrot16; Nila122; Michael Whitlock (bigbeargames); Matthew Krohn (makrohn); Johannes Sjölund (wulax)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 2.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-clothes-and-hair"
  },
  {
    "id": "outfit:ranger:t3:male",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/ranger_t3_male.png",
    "author": "JaidynReiman; bluecarrot16; Nila122; Michael Whitlock (bigbeargames); Matthew Krohn (makrohn); Johannes Sjölund (wulax)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 2.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-clothes-and-hair"
  },
  {
    "id": "outfit:ranger:t3:female",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/ranger_t3_female.png",
    "author": "JaidynReiman; bluecarrot16; Nila122; Michael Whitlock (bigbeargames); Matthew Krohn (makrohn); Johannes Sjölund (wulax)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 2.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-clothes-and-hair"
  },
  {
    "id": "outfit:mage:t0:male",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/mage_t0_male.png",
    "author": "JaidynReiman; bluecarrot16; Johannes Sjölund (wulax); Joe White; ElizaWy; Matthew Krohn (makrohn); Stephen Challener (Redshrike)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "outfit:mage:t0:female",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/mage_t0_female.png",
    "author": "JaidynReiman; bluecarrot16; Johannes Sjölund (wulax); Joe White; ElizaWy; Matthew Krohn (makrohn); Stephen Challener (Redshrike); Luke Mehl",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "outfit:mage:t1:male",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/mage_t1_male.png",
    "author": "JaidynReiman; bluecarrot16; Johannes Sjölund (wulax); Joe White; ElizaWy; Matthew Krohn (makrohn); Stephen Challener (Redshrike)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "outfit:mage:t1:female",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/mage_t1_female.png",
    "author": "JaidynReiman; bluecarrot16; Johannes Sjölund (wulax); Joe White; ElizaWy; Matthew Krohn (makrohn); Stephen Challener (Redshrike); Luke Mehl",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "outfit:mage:t2:male",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/mage_t2_male.png",
    "author": "Nila122; JaidynReiman; Matthew Krohn (makrohn); Johannes Sjölund (wulax); Stephen Challener (Redshrike); bluecarrot16",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 2.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-roman-armor"
  },
  {
    "id": "outfit:mage:t2:female",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/mage_t2_female.png",
    "author": "Nila122; JaidynReiman; Matthew Krohn (makrohn); Johannes Sjölund (wulax); Stephen Challener (Redshrike); Luke Mehl",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 2.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-roman-armor"
  },
  {
    "id": "outfit:mage:t3:male",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/mage_t3_male.png",
    "author": "Nila122; JaidynReiman; Matthew Krohn (makrohn); Johannes Sjölund (wulax); Stephen Challener (Redshrike); bluecarrot16",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 2.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-roman-armor"
  },
  {
    "id": "outfit:mage:t3:female",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/mage_t3_female.png",
    "author": "Nila122; JaidynReiman; Matthew Krohn (makrohn); Johannes Sjölund (wulax); Stephen Challener (Redshrike); Luke Mehl",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 2.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-roman-armor"
  },
  {
    "id": "outfit:healer:t0:male",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/healer_t0_male.png",
    "author": "JaidynReiman; bluecarrot16; Johannes Sjölund (wulax); Joe White; ElizaWy; Matthew Krohn (makrohn); Stephen Challener (Redshrike)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "outfit:healer:t0:female",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/healer_t0_female.png",
    "author": "JaidynReiman; bluecarrot16; Johannes Sjölund (wulax); Joe White; ElizaWy; Matthew Krohn (makrohn); Stephen Challener (Redshrike); Luke Mehl",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "outfit:healer:t1:male",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/healer_t1_male.png",
    "author": "JaidynReiman; bluecarrot16; Johannes Sjölund (wulax); Joe White; ElizaWy; Matthew Krohn (makrohn); Stephen Challener (Redshrike)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "outfit:healer:t1:female",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/healer_t1_female.png",
    "author": "JaidynReiman; bluecarrot16; Johannes Sjölund (wulax); Joe White; ElizaWy; Matthew Krohn (makrohn); Stephen Challener (Redshrike); Luke Mehl",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "outfit:healer:t2:male",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/healer_t2_male.png",
    "author": "Nila122; JaidynReiman; Matthew Krohn (makrohn); Johannes Sjölund (wulax); Stephen Challener (Redshrike); bluecarrot16",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 2.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-roman-armor"
  },
  {
    "id": "outfit:healer:t2:female",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/healer_t2_female.png",
    "author": "Nila122; JaidynReiman; Matthew Krohn (makrohn); Johannes Sjölund (wulax); Stephen Challener (Redshrike); Luke Mehl",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 2.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-roman-armor"
  },
  {
    "id": "outfit:healer:t3:male",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/healer_t3_male.png",
    "author": "Nila122; JaidynReiman; Matthew Krohn (makrohn); Johannes Sjölund (wulax); Stephen Challener (Redshrike); bluecarrot16",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 2.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-roman-armor"
  },
  {
    "id": "outfit:healer:t3:female",
    "category": "outfit",
    "zIndex": 40,
    "file": "/lpc/outfit/healer_t3_female.png",
    "author": "Nila122; JaidynReiman; Matthew Krohn (makrohn); Johannes Sjölund (wulax); Stephen Challener (Redshrike); Luke Mehl",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 2.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-roman-armor"
  },
  {
    "id": "gear:sword:male",
    "category": "weapon",
    "zIndex": 80,
    "file": "/lpc/gear/sword_male.png",
    "author": "ElizaWy; walk and down by JaidynReiman",
    "license": "OGA-BY 3.0",
    "sourceUrl": "https://github.com/ElizaWy/LPC/tree/main/Characters/Props/Sword%2001%20-%20Arming%20Sword"
  },
  {
    "id": "gear:sword:female",
    "category": "weapon",
    "zIndex": 80,
    "file": "/lpc/gear/sword_female.png",
    "author": "ElizaWy; walk and down by JaidynReiman",
    "license": "OGA-BY 3.0",
    "sourceUrl": "https://github.com/ElizaWy/LPC/tree/main/Characters/Props/Sword%2001%20-%20Arming%20Sword"
  },
  {
    "id": "gear:greatsword:male",
    "category": "weapon",
    "zIndex": 80,
    "file": "/lpc/gear/greatsword_male.png",
    "author": "Johannes Sjölund (wulax); bluecarrot16",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "gear:greatsword:female",
    "category": "weapon",
    "zIndex": 80,
    "file": "/lpc/gear/greatsword_female.png",
    "author": "Johannes Sjölund (wulax); bluecarrot16",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "gear:staff:male",
    "category": "weapon",
    "zIndex": 80,
    "file": "/lpc/gear/staff_male.png",
    "author": "bluecarrot16",
    "license": "OGA-BY 3.0+, GPL 3.0, CC-BY 4.0",
    "sourceUrl": "https://opengameart.org/content/lpc-more-weapons"
  },
  {
    "id": "gear:staff:female",
    "category": "weapon",
    "zIndex": 80,
    "file": "/lpc/gear/staff_female.png",
    "author": "bluecarrot16",
    "license": "OGA-BY 3.0+, GPL 3.0, CC-BY 4.0",
    "sourceUrl": "https://opengameart.org/content/lpc-more-weapons"
  },
  {
    "id": "gear:slingshot:male",
    "category": "weapon",
    "zIndex": 80,
    "file": "/lpc/gear/slingshot_male.png",
    "author": "bluecarrot16",
    "license": "OGA-BY 3.0+, GPL 3.0, CC-BY 4.0",
    "sourceUrl": "https://opengameart.org/content/lpc-more-weapons"
  },
  {
    "id": "gear:slingshot:female",
    "category": "weapon",
    "zIndex": 80,
    "file": "/lpc/gear/slingshot_female.png",
    "author": "bluecarrot16",
    "license": "OGA-BY 3.0+, GPL 3.0, CC-BY 4.0",
    "sourceUrl": "https://opengameart.org/content/lpc-more-weapons"
  },
  {
    "id": "gear:cap:male",
    "category": "helmet",
    "zIndex": 70,
    "file": "/lpc/gear/cap_male.png",
    "author": "Johannes Sjölund (wulax); Matthew Krohn (Makrohn); JaidynReiman",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "gear:cap:female",
    "category": "helmet",
    "zIndex": 70,
    "file": "/lpc/gear/cap_female.png",
    "author": "Johannes Sjölund (wulax); Matthew Krohn (Makrohn); JaidynReiman",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "gear:helm:male",
    "category": "helmet",
    "zIndex": 70,
    "file": "/lpc/gear/helm_male.png",
    "author": "bluecarrot16",
    "license": "OGA-BY 3.0, CC-BY 3.0, CC-BY 4.0, GPL 2.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-helmets"
  },
  {
    "id": "gear:helm:female",
    "category": "helmet",
    "zIndex": 70,
    "file": "/lpc/gear/helm_female.png",
    "author": "bluecarrot16",
    "license": "OGA-BY 3.0, CC-BY 3.0, CC-BY 4.0, GPL 2.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-helmets"
  },
  {
    "id": "gear:greathelm:male",
    "category": "helmet",
    "zIndex": 70,
    "file": "/lpc/gear/greathelm_male.png",
    "author": "bluecarrot16",
    "license": "OGA-BY 3.0, CC-BY 3.0, CC-BY 4.0, GPL 2.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-helmets"
  },
  {
    "id": "gear:greathelm:female",
    "category": "helmet",
    "zIndex": 70,
    "file": "/lpc/gear/greathelm_female.png",
    "author": "bluecarrot16",
    "license": "OGA-BY 3.0, CC-BY 3.0, CC-BY 4.0, GPL 2.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-helmets"
  },
  {
    "id": "gear:leather-armor:male",
    "category": "armor",
    "zIndex": 60,
    "file": "/lpc/gear/leather-armor_male.png",
    "author": "Johannes Sjölund (wulax); bluecarrot16; JaidynReiman; Michael Whitlock (bigbeargames); Matthew Krohn (makrohn)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "gear:leather-armor:female",
    "category": "armor",
    "zIndex": 60,
    "file": "/lpc/gear/leather-armor_female.png",
    "author": "Johannes Sjölund (wulax); bluecarrot16; JaidynReiman; Michael Whitlock (bigbeargames); Matthew Krohn (makrohn)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "gear:mail:male",
    "category": "armor",
    "zIndex": 60,
    "file": "/lpc/gear/mail_male.png",
    "author": "Johannes Sjölund (wulax); Napsio (Vitruvian Studio); JaidynReiman",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "gear:mail:female",
    "category": "armor",
    "zIndex": 60,
    "file": "/lpc/gear/mail_female.png",
    "author": "Johannes Sjölund (wulax); Napsio (Vitruvian Studio); JaidynReiman",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "gear:plate:male",
    "category": "armor",
    "zIndex": 60,
    "file": "/lpc/gear/plate_male.png",
    "author": "Napsio (Vitruvian Studio); JaidynReiman; bluecarrot16; Michael Whitlock (bigbeargames); Johannes Sjölund (wulax); Matthew Krohn (makrohn)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "gear:plate:female",
    "category": "armor",
    "zIndex": 60,
    "file": "/lpc/gear/plate_female.png",
    "author": "Napsio (Vitruvian Studio); JaidynReiman; bluecarrot16; Michael Whitlock (bigbeargames); Johannes Sjölund (wulax); Matthew Krohn (makrohn)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "gear:shoes:male",
    "category": "boots",
    "zIndex": 50,
    "file": "/lpc/gear/shoes_male.png",
    "author": "JaidynReiman; bluecarrot16; Johannes Sjölund (wulax); Joe White",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "gear:shoes:female",
    "category": "boots",
    "zIndex": 50,
    "file": "/lpc/gear/shoes_female.png",
    "author": "JaidynReiman; bluecarrot16; Johannes Sjölund (wulax); Joe White",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "gear:boots:male",
    "category": "boots",
    "zIndex": 50,
    "file": "/lpc/gear/boots_male.png",
    "author": "JaidynReiman; bluecarrot16; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 2.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-clothes-and-hair"
  },
  {
    "id": "gear:boots:female",
    "category": "boots",
    "zIndex": 50,
    "file": "/lpc/gear/boots_female.png",
    "author": "JaidynReiman; bluecarrot16; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 2.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-clothes-and-hair"
  },
  {
    "id": "gear:greaves:male",
    "category": "boots",
    "zIndex": 50,
    "file": "/lpc/gear/greaves_male.png",
    "author": "Matthew Krohn (makrohn); Johannes Sjölund (wulax)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "gear:greaves:female",
    "category": "boots",
    "zIndex": 50,
    "file": "/lpc/gear/greaves_female.png",
    "author": "Matthew Krohn (makrohn); Johannes Sjölund (wulax)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "gear:cape:male",
    "category": "accessory",
    "zIndex": 90,
    "file": "/lpc/gear/cape_male.png",
    "author": "bluecarrot16; JaidynReiman",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-curly-hair-elven-ears-white-cape-with-blue-trim-and-more"
  },
  {
    "id": "gear:cape:female",
    "category": "accessory",
    "zIndex": 90,
    "file": "/lpc/gear/cape_female.png",
    "author": "bluecarrot16; JaidynReiman",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-curly-hair-elven-ears-white-cape-with-blue-trim-and-more"
  },
  {
    "id": "gear:amulet:male",
    "category": "accessory",
    "zIndex": 90,
    "file": "/lpc/gear/amulet_male.png",
    "author": "bluecarrot16; AntumDeluge",
    "license": "CC0",
    "sourceUrl": "https://opengameart.org/content/dungeon-crawl-32x32-tiles"
  },
  {
    "id": "gear:amulet:female",
    "category": "accessory",
    "zIndex": 90,
    "file": "/lpc/gear/amulet_female.png",
    "author": "bluecarrot16; AntumDeluge",
    "license": "CC0",
    "sourceUrl": "https://opengameart.org/content/dungeon-crawl-32x32-tiles"
  },
  {
    "id": "gear:excalibur:male",
    "category": "weapon",
    "zIndex": 80,
    "file": "/lpc/gear/excalibur_male.png",
    "author": "bluecarrot16; tskaufma; Johannes Sjölund (wulax)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "gear:excalibur:female",
    "category": "weapon",
    "zIndex": 80,
    "file": "/lpc/gear/excalibur_female.png",
    "author": "bluecarrot16; tskaufma; Johannes Sjölund (wulax)",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites"
  },
  {
    "id": "gear:archmage-staff:male",
    "category": "weapon",
    "zIndex": 80,
    "file": "/lpc/gear/archmage-staff_male.png",
    "author": "bluecarrot16",
    "license": "OGA-BY 3.0+, GPL 3.0, CC-BY 4.0",
    "sourceUrl": "https://opengameart.org/content/lpc-more-weapons"
  },
  {
    "id": "gear:archmage-staff:female",
    "category": "weapon",
    "zIndex": 80,
    "file": "/lpc/gear/archmage-staff_female.png",
    "author": "bluecarrot16",
    "license": "OGA-BY 3.0+, GPL 3.0, CC-BY 4.0",
    "sourceUrl": "https://opengameart.org/content/lpc-more-weapons"
  },
  {
    "id": "gear:dragon-plate:male",
    "category": "armor",
    "zIndex": 60,
    "file": "/lpc/gear/dragon-plate_male.png",
    "author": "Napsio (Vitruvian Studio); JaidynReiman; bluecarrot16; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 2.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-roman-armor"
  },
  {
    "id": "gear:dragon-plate:female",
    "category": "armor",
    "zIndex": 60,
    "file": "/lpc/gear/dragon-plate_female.png",
    "author": "Napsio (Vitruvian Studio); JaidynReiman; bluecarrot16; Nila122",
    "license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 2.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/lpc-roman-armor"
  },
  {
    "id": "gear:crown:male",
    "category": "helmet",
    "zIndex": 70,
    "file": "/lpc/gear/crown_male.png",
    "author": "DarkwallLKE; Charles Sanchez (CharlesGabriel)",
    "license": "CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/liberated-pixel-cup-lpc-base-assets-sprites-map-tiles"
  },
  {
    "id": "gear:crown:female",
    "category": "helmet",
    "zIndex": 70,
    "file": "/lpc/gear/crown_female.png",
    "author": "DarkwallLKE; Charles Sanchez (CharlesGabriel)",
    "license": "CC-BY-SA 3.0, GPL 3.0",
    "sourceUrl": "https://opengameart.org/content/liberated-pixel-cup-lpc-base-assets-sprites-map-tiles"
  }
];

export const catalogById: Map<string, CatalogEntry> = new Map(
  CATALOG.map((e) => [e.id, e]),
);
