// GENERATED by scripts/src/build-kingdom-buildings.ts — do not edit by hand.
// Regenerate with: pnpm --filter @workspace/scripts build-kingdom-buildings

export type BuildingSprite = { url: string; w: number; h: number };

export const BUILDING_SPRITES: Record<string, BuildingSprite> = {
  "build.hut-stone": { url: "/kingdoms/buildings/hut-stone.png", w: 80, h: 102 },
  "build.house-stone": { url: "/kingdoms/buildings/house-stone.png", w: 112, h: 118 },
  "build.hall-stone": { url: "/kingdoms/buildings/hall-stone.png", w: 144, h: 126 },
  "build.tower-stone": { url: "/kingdoms/buildings/tower-stone.png", w: 64, h: 166 },
  "build.keep-stone": { url: "/kingdoms/buildings/keep-stone.png", w: 176, h: 142 },
  "build.hut-gold": { url: "/kingdoms/buildings/hut-gold.png", w: 80, h: 102 },
  "build.house-gold": { url: "/kingdoms/buildings/house-gold.png", w: 112, h: 118 },
  "build.hall-gold": { url: "/kingdoms/buildings/hall-gold.png", w: 144, h: 126 },
  "build.tower-gold": { url: "/kingdoms/buildings/tower-gold.png", w: 64, h: 166 },
  "build.keep-gold": { url: "/kingdoms/buildings/keep-gold.png", w: 176, h: 142 },
  "build.hut-slate": { url: "/kingdoms/buildings/hut-slate.png", w: 80, h: 102 },
  "build.house-slate": { url: "/kingdoms/buildings/house-slate.png", w: 112, h: 118 },
  "build.hall-slate": { url: "/kingdoms/buildings/hall-slate.png", w: 144, h: 126 },
  "build.tower-slate": { url: "/kingdoms/buildings/tower-slate.png", w: 64, h: 166 },
  "build.keep-slate": { url: "/kingdoms/buildings/keep-slate.png", w: 176, h: 142 },
  "build.hut-brown": { url: "/kingdoms/buildings/hut-brown.png", w: 80, h: 102 },
  "build.house-brown": { url: "/kingdoms/buildings/house-brown.png", w: 112, h: 118 },
  "build.hall-brown": { url: "/kingdoms/buildings/hall-brown.png", w: 144, h: 126 },
  "build.tower-brown": { url: "/kingdoms/buildings/tower-brown.png", w: 64, h: 166 },
  "build.keep-brown": { url: "/kingdoms/buildings/keep-brown.png", w: 176, h: 142 },
  "build.hut-dark": { url: "/kingdoms/buildings/hut-dark.png", w: 80, h: 102 },
  "build.house-dark": { url: "/kingdoms/buildings/house-dark.png", w: 112, h: 118 },
  "build.hall-dark": { url: "/kingdoms/buildings/hall-dark.png", w: 144, h: 126 },
  "build.tower-dark": { url: "/kingdoms/buildings/tower-dark.png", w: 64, h: 166 },
  "build.keep-dark": { url: "/kingdoms/buildings/keep-dark.png", w: 176, h: 142 },
  "build.hut-brick": { url: "/kingdoms/buildings/hut-brick.png", w: 80, h: 102 },
  "build.house-brick": { url: "/kingdoms/buildings/house-brick.png", w: 112, h: 118 },
  "build.hall-brick": { url: "/kingdoms/buildings/hall-brick.png", w: 144, h: 126 },
  "build.tower-brick": { url: "/kingdoms/buildings/tower-brick.png", w: 64, h: 166 },
  "build.keep-brick": { url: "/kingdoms/buildings/keep-brick.png", w: 176, h: 142 },
};

export const BUILDING_SHAPES = ["hut", "house", "hall", "tower", "keep"] as const;
export const BUILDING_VARIANTS = ["stone", "gold", "slate", "brown", "dark", "brick"] as const;
