// GENERATED by scripts/src/build-kingdom-buildings.ts — do not edit by hand.
// Regenerate with: pnpm --filter @workspace/scripts build-kingdom-buildings

export type BuildingSprite = { url: string; w: number; h: number };

export const BUILDING_SPRITES: Record<string, BuildingSprite> = {
  "build.hut-stone": { url: "/kingdoms/buildings/hut-stone.png", w: 56, h: 60 },
  "build.house-stone": { url: "/kingdoms/buildings/house-stone.png", w: 72, h: 76 },
  "build.hall-stone": { url: "/kingdoms/buildings/hall-stone.png", w: 92, h: 84 },
  "build.tower-stone": { url: "/kingdoms/buildings/tower-stone.png", w: 44, h: 108 },
  "build.keep-stone": { url: "/kingdoms/buildings/keep-stone.png", w: 112, h: 96 },
  "build.hut-gold": { url: "/kingdoms/buildings/hut-gold.png", w: 56, h: 60 },
  "build.house-gold": { url: "/kingdoms/buildings/house-gold.png", w: 72, h: 76 },
  "build.hall-gold": { url: "/kingdoms/buildings/hall-gold.png", w: 92, h: 84 },
  "build.tower-gold": { url: "/kingdoms/buildings/tower-gold.png", w: 44, h: 108 },
  "build.keep-gold": { url: "/kingdoms/buildings/keep-gold.png", w: 112, h: 96 },
  "build.hut-slate": { url: "/kingdoms/buildings/hut-slate.png", w: 56, h: 60 },
  "build.house-slate": { url: "/kingdoms/buildings/house-slate.png", w: 72, h: 76 },
  "build.hall-slate": { url: "/kingdoms/buildings/hall-slate.png", w: 92, h: 84 },
  "build.tower-slate": { url: "/kingdoms/buildings/tower-slate.png", w: 44, h: 108 },
  "build.keep-slate": { url: "/kingdoms/buildings/keep-slate.png", w: 112, h: 96 },
  "build.hut-brown": { url: "/kingdoms/buildings/hut-brown.png", w: 56, h: 60 },
  "build.house-brown": { url: "/kingdoms/buildings/house-brown.png", w: 72, h: 76 },
  "build.hall-brown": { url: "/kingdoms/buildings/hall-brown.png", w: 92, h: 84 },
  "build.tower-brown": { url: "/kingdoms/buildings/tower-brown.png", w: 44, h: 108 },
  "build.keep-brown": { url: "/kingdoms/buildings/keep-brown.png", w: 112, h: 96 },
  "build.hut-dark": { url: "/kingdoms/buildings/hut-dark.png", w: 56, h: 60 },
  "build.house-dark": { url: "/kingdoms/buildings/house-dark.png", w: 72, h: 76 },
  "build.hall-dark": { url: "/kingdoms/buildings/hall-dark.png", w: 92, h: 84 },
  "build.tower-dark": { url: "/kingdoms/buildings/tower-dark.png", w: 44, h: 108 },
  "build.keep-dark": { url: "/kingdoms/buildings/keep-dark.png", w: 112, h: 96 },
  "build.hut-brick": { url: "/kingdoms/buildings/hut-brick.png", w: 56, h: 60 },
  "build.house-brick": { url: "/kingdoms/buildings/house-brick.png", w: 72, h: 76 },
  "build.hall-brick": { url: "/kingdoms/buildings/hall-brick.png", w: 92, h: 84 },
  "build.tower-brick": { url: "/kingdoms/buildings/tower-brick.png", w: 44, h: 108 },
  "build.keep-brick": { url: "/kingdoms/buildings/keep-brick.png", w: 112, h: 96 },
};
